opengenusWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from pages.views import InternListView,InternDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('index', TemplateView.as_view(template_name="index.html")),
    path('cosmos', TemplateView.as_view(template_name="cosmos.html"), name="cosmos"),
    path('quark', TemplateView.as_view(template_name="quark.html"), name="quark"),
    path('search', TemplateView.as_view(template_name="search.html"), name="search"),
    path('iq', TemplateView.as_view(template_name="iq.html"), name="iq"),
    path('discuss', TemplateView.as_view(template_name="discuss.html"), name="discuss"),
    # path('intern/<str:username>', internDetailView),
    path('school/', include('schools.urls', namespace="schools")),
    path('intern/', InternListView.as_view()),
    path('intern/<str:slug>', InternDetailView.as_view()),
    path('intern/search/<query>', InternListView.as_view()),
    path('faq', TemplateView.as_view(template_name="faq.html"), name="faq"),

    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schools/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView
from django.conf import settings
from django.urls import path,resolve
from django.conf.urls.static import static

from .views import (SchoolDetailView,SchoolInternView,SchoolListView)

app_name = 'schools'
urlpatterns = [
    path('', SchoolListView.as_view()),
    path('<slug:url_endpoint>/', SchoolDetailView.as_view(), name='detail'),
    path('<slug:url_endpoint>/interns', SchoolInternView.as_view(), name='asso-interns'),
    path('search/<query>/',SchoolListView.as_view(), name='search')
    # url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/update$', ItemUpdateView.as_view(), name='update'),
    # url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
    # url(r'^$', ItemListView.as_view(), name='list'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models
from django.urls import reverse
from schools.models import school

POSITION_CHOICES=(
	('Intern','INTERN'),
	('Software developer','SOFTWARE DEVELOPER'),
	('Founder','FOUNDER'),
	)
# Create your models here.
class intern(models.Model):
	username		=	models.CharField(max_length=120,unique=True)
	name			=	models.CharField(max_length=120) 
	discourse_url	=	models.URLField(max_length=120,unique=True)
	location		=	models.CharField(max_length=120)
	introduction	=	models.TextField(max_length=1000)
	position		=	models.CharField(max_length=30, choices=POSITION_CHOICES,default='Intern')
	start_date		= 	models.DateField(max_length=120)
	finish_date		= 	models.DateField(max_length=120)
	picture_upload	=	models.ImageField(null=True,blank=True,
											height_field="height_field",
											width_field="width_field")
	work_done		=	models.CharField(max_length=120)
	fav_experience	=	models.TextField(max_length=1000,null=True,blank=True)
	height_field	=	models.IntegerField(default=0)
	width_field		=	models.IntegerField(default=0)
	latest_school	=	models.ForeignKey(school, on_delete = models.CASCADE, related_name='latest_school', default=1)
	prev_school_1	=	models.ForeignKey(school, on_delete = models.CASCADE, 
										null=True, blank=True,related_name='prev_school_1')
	prev_school_2	=	models.ForeignKey(school, on_delete = models.CASCADE,
										null=True, blank=True, related_name='prev_school_2')

	def __str__(self):
		return self.name

	class Meta:
		ordering = ["-finish_date"]

	def get_absolute_url(self):
		return reverse('intern-detail',args=[str(self.username)])

	def save(self, *args, **kwargs):
		self.username = self.username.lower()
		super().save(*args, **kwargs)

# class Schools(models.Model):
# 	full name			=	models.CharField(max_length=120, unique=True) 
# 	short name			=	models.CharField(max_length=30, unique=True)
# 	url_id				=	models.URLField(max_length=120, unique=True)
# 	description			=	models.TextField(max_length=500)
# 	location			=	models.CharField(max_length=120)
# 	official_link		=	models.URLField(max_length=120, unique=True)
# 	logo_picture		=	models.
# 	established_date

schools/models.py
from django.db import models
from django.db.models.signals import pre_save

from tinymce.models import HTMLField
from tinymce.widgets import TinyMCE
from tinymce import models as tinymce_models


from .utils import unique_slug_generator


# Create your models here.
class school(models.Model):
	full_name			=	models.CharField(max_length=120, unique=True)
	short_name			=	models.CharField(max_length=120, unique=True)
	url_endpoint		=	models.SlugField(null=True,blank=True)
	# description			=	models.TextField(max_length=1000)
	location			=	models.CharField(max_length=30)
	official_link		=	models.URLField(max_length=120,unique=True)
	logo_picture		=	models.ImageField(null=True,blank=True,
											height_field="height_field",
											width_field="width_field")
	height_field		=	models.IntegerField(default=0)
	width_field			=	models.IntegerField(default=0)
	established_date	=	models.DateField()
	description			=	HTMLField(null=True,blank=True)
	opengenus_rating    =   models.FloatField(default=0)


	def __str__(self):
		return self.full_name

	def get_rating_perc(self):
		return int((self.opengenus_rating/5)*100)

	class Meta:
		ordering = ["-established_date"]

def school_pre_save_receiver(sender, instance, *args,**kwargs):
	if not instance.url_endpoint:
		instance.url_endpoint = unique_slug_generator(instance)


pre_save.connect(school_pre_save_receiver, sender=school)

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView,DetailView

from pages.models import intern
from schools.models import school
# Create your views here.

def internDetailView(request,username):
	return HttpResponse("Hi")
# class InternDetailView(DetailView):
# 	return HttpResponse("Hi")

class InternListView(ListView):
	paginate_by=2
	def get_queryset(self):
		if len(self.kwargs) > 0:
			return intern.objects.filter(name__icontains=self.kwargs['query'])
		else:
			return intern.objects.all()

class InternDetailView(DetailView):
	queryset = intern.objects.all()
	slug_field = 'username'

schools/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import resolve
from django.views.generic import ListView, DetailView

from .models import school

# Create your views here.
class SchoolDetailView(DetailView):
	queryset = school.objects.all()

	def get_object(self):
		object = get_object_or_404(school, url_endpoint=self.kwargs['url_endpoint'])
		return object


class SchoolInternView(ListView):
	template_name = "schools/school_listmk.html"
	def get_queryset(self):
		# qs= school.objects.filter(url_endpoint="dps").first()
		# current_url = resolve(request.path_info).url_name
		# print(current_url)
		school_name=self.kwargs['url_endpoint']
		qs= school.objects.filter(url_endpoint=school_name).first()
		print(school_name)
		queryset = qs.latest_school.all()
		return queryset

class SchoolListView(ListView):
    paginate_by=2

    def get_queryset(self):
        if len(self.kwargs) > 0:
            return school.objects.filter(full_name__icontains=self.kwargs['query'])
        else:
            return school.objects.all()

templates/base.html
<!Doctype HTML>

<html>
<head>
	{% block head %}
		{% include "snippets/css.html" %}
		{% include "snippets/js.html" %}
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, user-scalable=no">
		<link rel="shortcut icon" type="image/png" href="/static/image/favicon.png"/>
	{% endblock head%}
</head>
<title>{% block head_title %}OpenGenus Foundation{% endblock head_title%}</title>

{% block header %}
	<header>
        <nav class="navbar navbar-light bg-light navbar-expand-lg navbar-fixed-top">
					<a href="{% url 'home' %}" class="navbar-brand mr-auto">
						 <img src="/static/image/og_logo.png" alt="Open Genus" style="height:2.57rem;width:auto;" class="img-fluid">
					</a>

          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#headerNav" aria-controls="headerNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div id="headerNav" class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav ml-auto">

              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'home' %}active{% endif %}" href="{% url 'home' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'quark' %}active{% endif %}" href="{% url 'quark' %}">Quark</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'cosmos' %}active{% endif %}" href="{% url 'cosmos' %}">Cosmos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'iq' %}active{% endif %}" href="{% url 'iq' %}">IQ</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'discuss' %}active{% endif %}" href="{% url 'discuss' %}">Discuss</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'search' %}active{% endif %}" href="{% url 'search' %}">Search Engine</a>
              </li>

            </ul>
          </div>
        </nav>
	</header>
{% endblock header %}


{% block content %}
	{% block first_section %}
		{% block first_section_upper %}
		  <section class="hero">
		    <div class="jumbotron jumbotron-fluid mb-0">
		      <div class="container">
		        <div class="row justify-content-center text-center">
		          <div class="col-md-10 col-lg-6">
		{% endblock first_section_upper %}

	   {% block first_section_lower %}
	            <p class="lead">
	            	<a href="https://github.com/opengenus" target="_blank"><i class="fa fa-3x fa-github-square"></i></a>
	            	<a href="https://twitter.com/opengenus" target="_blank"><i class="fa fa-3x fa-twitter-square"></i></a>
			      		<a href="https://discourse.opengenus.org" target="_blank"><i class="fa fa-3x fa-commenting-o"></i></a>
			      		<a href="mailto:team@opengenus.org" target="_blank"><i class="fa fa-3x fa-envelope"></i></a>
	            </p>
	         		</div>
	        	</div>
	      	</div>
	    	</div>
	  	</section>
	  {% endblock first_section_lower %}
	{% endblock first_section %}

  {% block second_section %}
  	{% block second_section_upper %}
			<section id="sec-about" class="sec-about pt-5 pb-5">
				<div class="container">
					<div class="row justify-content-center text-center">
						<div class="col-md-10 col-lg-8">
    {% endblock second_section_upper %}

		{% block second_section_lower %}
						</div>
					</div>
				</div>
			</section>
  	{% endblock second_section_lower %}
  {% endblock second_section %}

{% endblock content%}


{% block press_section %}
  <br><br><br><br>

  <section id="sec-contact" class="sec-contact pt-5 pb-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10 col-lg-7">
          <h1 class="h4">For press enquiry, story tips and anything else, contact us at team@opengenus.org </h1>
        </div>
      </div>
    </div>
  </section>

  <br><br><br><br><br><br>
{% endblock press_section %}

<footer class="footer fixed-bottom">
	{% block footer %}
	<ul class="list-inline mb-0 text-center">

        <li class="list-inline-item">
          <a href="https://twitter.com/opengenus" target="_blank"><span class="fa fa-2x fa-twitter social_link"></span></a>
        </li>

        <li class="list-inline-item">
          <a href="https://github.com/opengenus" target="_blank"><span class="fa fa-2x fa-github-square social_link"></span></a>
        </li>

        <li class="list-inline-item">
          <a href="https://www.linkedin.com/company/opengenus" target="_blank"><span class="fa fa-2x fa-linkedin social_link"></span></a>
        </li>

        <li class="list-inline-item">
          <a href="mailto:team@opengenus.org" target="_blank"><span class="fa fa-2x fa-envelope-o social_link"></span></a>
        </li>
      </ul>
	{% endblock footer %}

</footer>
</html>

templates/cosmos.html
{% extends "base.html" %}

<head>
{% block head %}
    {{ block.super }}  
{% endblock head %}
</head>

{% block header %}
      {{ block.super }}
{% endblock header %}


{% block content %}
  {% block first_section %}
    {% block first_section_upper %}
      {{block.super}}
    {% endblock first_section_upper %}

      <h1 class="display-5">Cosmos</h1>
      <h5 style="color: white !important;" class="display-5">by OpenGenus Foundation</h5>

      <p class="lead">The Algorithms that run our Universe</p>

    {% block first_section_lower %}
      {{block.super}}
    {% endblock first_section_lower %}
  {% endblock first_section %}

  {% block second_section %}
    {% block second_section_upper %}
      {{block.super}}
    {% endblock second_section_upper %}
          <h1 class="h4">About Cosmos</h1>
          <p class="mt-4 mb-4">
            Cosmos is your personal offline collection of every algorithm and data structure one will ever encounter and use in a lifetime. This provides solutions in various languages spanning C, C++, Java, JavaScript, Swift, Python, Go and many others.
            <br><br>
            <strong>Over 800 happy awesome people have contributed to Cosmos.</strong>

            <br><br>

            This work is maintained by a community of hundreds of people and is a massive collaborative effort to bring the readily available coding knowledge offline.

            <br><br>
            <strong>Cosmos is one of the most popular open-source projects with over 7000 stars and 800 contributors.</strong>

            <br><br>
            Currently, we have 5 active maintainers and we are expanding quickly. The task of maintainers is to review pull requests, suggest further quality additions and keep the work up to date with the current state of the world. You can, also, join us as a maintainer.

            <br><br>
            <strong>Contributing to Cosmos is one of the most easy and learning intensive task.</strong>

            Check out Cosmos and help us develop it to be the best:<br><br>

            <div class="pro">
              <div id="carouselExampleIndicators" class="carousel slide" data-interval="3000" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block" src="static/image/cosmos.png" alt="First slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block" src="static/image/cosmos.png" alt="Second slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block" src="static/image/cosmos.png" alt="Third slide">
                  </div>
                </div>
              </div>
            </div>
            <br><br><br>
             <p class="lead">
              <a class="btn btn-primary btn-lg" href="https:github.com/opengenus/cosmos" target="_blank" role="button">Cosmos on GitHub</a>
            </p>

            <div class="contributors py-4">
              <h1 class="h4">Cosmos Contributors</h1>
              {% for d in data.data %}
                  <a href={{d.link}} target="_blank" class="d-inline-block my-1" data-toggle="tooltip" title="Contributions: {{d.contributions}}"  style="width:6%;"><img src={{d.user_image}} alt={{d.name}} class="rounded-circle mw-100 mh-100" /></a>
              {% endfor %}
            </div>

          </p>
    {% block second_section_lower %}
      {{block.super}}
    {% endblock second_section_lower %}
  {% endblock second_section %}

{% endblock content %}

{% block press_section %}{{ block.super }}{% endblock press_section %}

<footer>{% block footer %}{{ block.super }}{% endblock footer %}</footer>

templates/discuss.html
{% extends "base.html" %}

<head>
{% block head %}
    {{ block.super }}  
{% endblock head %}
</head>

{% block header %}
      {{ block.super }}
{% endblock header %}

{% block content %}
  {% block first_section %}
    {% block first_section_upper %}
      {{block.super}}
    {% endblock first_section_upper %}

          <h1 class="display-5">Discuss</h1>
          <h5 style="color: white !important;" class="display-5">by OpenGenus Foundation</h5>

          <p class="lead">The Algorithms that run our Universe</p>

    {% block first_section_lower %}
      {{block.super}}
    {% endblock first_section_lower %}
  {% endblock first_section %}


  <section id="sec-about" class="sec-about pt-5 pb-5">
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-md-10 col-lg-8">
          <h1 class="h4">About us</h1>
          <p class="mt-4 mb-4">
            Cosmos is your personal offline collection of every algorithm and data structure one will ever encounter and use in a lifetime. This provides solutions in various languages spanning C, C++, Java, JavaScript, Swift, Python, Go and many others.
            <br><br>
            <strong>Over 800 happy awesome people have contributed to Cosmos.</strong>

            <br><br>

            This work is maintained by a community of hundreds of people and is a massive collaborative effort to bring the readily available coding knowledge offline.

            <br><br>
            <strong>Cosmos is one of the most popular open-source projects with over 7000 stars and 800 contributors.</strong>

            <br><br>
            Currently, we have 5 active maintainers and we are expanding quickly. The task of maintainers is to review pull requests, suggest further quality additions and keep the work up to date with the current state of the world. You can, also, join us as a maintainer. 

            <br><br>
            <strong>Contributing to Cosmos is one of the most easy and learning intensive task.</strong>

            Check out Cosmos and help us develop it to be the best:<br><br>

            <div class="pro"><img src="/static/image/cosmos.png"></div>

             <p class="lead">
              <a class="btn btn-primary btn-lg" href="https:github.com/opengenus/cosmos" target="_blank" role="button">Cosmos on GitHub</a>
            </p>

          </p>
        </div>
      </div>

      
    </div>
  </section>
{% endblock content %}

{% block press_section %}{{ block.super }}{% endblock press_section %}

<footer>{% block footer %}{{ block.super }}{% endblock footer %}</footer>

templates/faq.html
{% extends "base.html" %}
<head>
  {% block head %}
      {{ block.super }}
  {% endblock head %}
</head>

{% block header %}
      {{ block.super }}
{% endblock header %}

{% block content %}
  {% block first_section %}
    {% block first_section_upper %}
      {{block.super}}
    {% endblock first_section_upper %}

      <h1 class="display-5">FAQ</h1>
      <h5 style="color: white !important;" class="display-5">by OpenGenus Foundation</h5>

    {% block first_section_lower %}
      {{block.super}}
  {% endblock first_section_lower %}
{% endblock first_section %}

  {% block second_section %}
    {% block second_section_upper %}
      {{block.super}}
    {% endblock second_section_upper %}
<div class="container faq_section">
  <div class="FaQ_Each">
    <section class="box">
      <span>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <i class="fa fa-minus" id="other" aria-hidden="true"></i>
      </span>
      &nbsp;&nbsp;<span>What is OpenGenus Foundation ?</span>
    </section>
    <section class="draw">
      OpenGenus Foundation is an open-source non-profit organization with the aim to enable people to work offline for a longer stretch, reduce the time spent on searching by exploiting the fact that almost 90% of the searches are same for every generation and to make programming more accessible.
    </section>
  </div>
  <div class="FaQ_Each">
    <section class="box">
      <span>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <i class="fa fa-minus" id="other" aria-hidden="true"></i>
      </span>
      &nbsp;&nbsp;<span>What is OpenGenus Foundation about ?</span>
    </section>
    <section class="draw">
      OpenGenus is all about positivity and innovation.
    </section>
  </div>
  <div class="FaQ_Each">
    <section class="box">
      <span>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <i class="fa fa-minus" id="other" aria-hidden="true"></i>
      </span>
      &nbsp;&nbsp;<span>More about OpenGenus ?</span>
    </section>
    <section class="draw">
      Over 800 people have contributed to our missions and joined our family. We have been sponsored by three great companies namely Discourse, GitHub and DigitalOcean. We run one of the most popular open-source projects and have made a positive impact over people's life.
    </section>
  </div>
</div>
    {% block second_section_lower %}
      {{block.super}}
    {% endblock second_section_lower %}
  {% endblock second_section %}

{% endblock content %}

{% block press_section %}{{ block.super }}{% endblock press_section %}

<footer>{% block footer %}{{ block.super }}{% endblock footer %}</footer>

templates/iq.html
{% extends "base.html" %}
<head>
  {% block head %}
      {{ block.super }}
  {% endblock head %}
</head>

{% block header %}
      {{ block.super }}
{% endblock header %}

{% block content %}
  {% block first_section %}
    {% block first_section_upper %}
      {{block.super}}
    {% endblock first_section_upper %}

      <h1 class="display-5">IQ</h1>
      <h5 style="color: white !important;" class="display-5">by OpenGenus Foundation</h5>
      <p class="lead">Information at scale</p>

    {% block first_section_lower %}
      {{block.super}}
  {% endblock first_section_lower %}
{% endblock first_section %}

  {% block second_section %}
    {% block second_section_upper %}
      {{block.super}}
    {% endblock second_section_upper %}
        <h1 class="h4">About IQ</h1>
        <p class="mt-4 mb-4">
          Information at scale: We are on a mission to enhance learning ability and solve the problem of information loss forever. Learn computer science concepts at scale with simplicity and innovation.
          
          <br><br>
           <p class="lead">
            <a class="btn btn-primary btn-lg" href="http://iq.opengenus.org/" target="_blank" role="button">IQ on Web</a>
          </p>
        </p>      
    {% block second_section_lower %}
      {{block.super}}
    {% endblock second_section_lower %}
  {% endblock second_section %}

{% endblock content %}

{% block press_section %}{{ block.super }}{% endblock press_section %}

<footer>{% block footer %}{{ block.super }}{% endblock footer %}</footer>

templates/pages/intern_detail.html
{% extends "base.html" %}

<head>{% load static %}
    {% block head %}
    {{ block.super }}
{% endblock head %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,500" rel="stylesheet">
    <meta name="description" content="OpenGenus Internship {{object.username}} {{object.position}} {{object.about}} ">
    <meta name="keywords" content="OpenGenus, open-source, communities, internship, {{object.username}}, {{object.position}}">
  </head>

  <title>{% block head_title %}{{ block.super }}: {{object.username}}{% endblock head_title %}</title>
{% block header %}
    {{ block.super }}
{% endblock header %}

{% block content %}
<br><br>
  <body>
    <div class="fluid-container p-5" >
      <div class="row p-1">
        <div class="col-sm-12 col-md-3">
          <div class="px-3">
            {% if obj.picture_upload %}
              <img src="{{ object.picture_upload.url }}" style="height:235px;width:130px;" class="rounded w-100 mb-4">
            {% else %}
              <img src="/static/user/intern/picture/intern1.jpeg" style="height:235px;width:130px;" class="rounded w-100 mb-4">
            {% endif %}
            <h3 class="p-3 mb-2">{{object.name}}</h5>
            <h4 class="p-3 mb-2 capitalize">{{object.position}}</h6>
            <h5 class="p-3 mb-2">{{object.start_date}} - {{object.finish_date}}</h6>
            <!-- <a href="{{ object.discourse_url }}" target="_blank"><button type="button" class="btn btn-primary btn-md btn-block mt-4 rounded-0 disclosure font-weight-light">Talk on Discourse</button></a> -->
            <a href="{{ object.discourse_url }}" target="_blank"><button type="button" class="btn btn-block btn-md btn-lg">Talk on Discourse</button></a>
          </div>
        </div>
        <div class="col-sm-12 col-md-9">
          <div class="p-2">
            <h5 class="heading pl-3">About {{object.username}}</h5>
            <p class="pl-3 description py-1">{{object.introduction}}</p>
          </div>
          <div class="p-2">
            <h5 class="heading pl-3">Projects</h5>
            <p class="pl-3 description py-1">{{object.work_done}}</p>
          </div>
          <div class="p-2">
            <h5 class="heading pl-3">Favorite Experience</h5>
            <p class="pl-3 description py-1">{{object.fav_experience}}</p>
          </div>
          <p>{{ object.name }} is associated with <a href='{% url "schools:detail" object.latest_school.url_endpoint %}'>{{ object.latest_school }}</p>
        </div>
      </div>
  </body>
{% endblock content %}

{% block press_section %}
{% endblock press_section %}

<footer>
{% block footer %}
  {{ block.super }}
{% endblock footer %}
</footer>

templates/pages/interns_detail.html
{% extends "base.html" %}

<head>{% load static %}
    {% block head %}
    {{ block.super }}  
{% endblock head %}    
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,500" rel="stylesheet">
    <meta name="description" content="OpenGenus Internship {{object.username}} {{object.position}} {{object.about}} ">
    <meta name="keywords" content="OpenGenus, open-source, communities, internship, {{object.username}}, {{object.position}}">
  </head>

  <title>{% block head_title %}{{ block.super }}: {{object.username}}{% endblock head_title %}</title>
{% block header %}
    {{ block.super }}
{% endblock header %}

{% block content %}
<br><br>
  <body>
    <div class="fluid-container p-5" >
      <div class="row p-1">
        <div class="col-sm-12 col-md-3">
          <div class="px-3">
            <img src="{{ object.picture_upload.url }}" style="height:235px;width:130px;" class="rounded w-100 mb-4">
            <h3 class="p-3 mb-2">{{object.name}}</h5>
            <h4 class="p-3 mb-2 capitalize">{{object.position}}</h6>
            <h5 class="p-3 mb-2">{{object.start_date}} - {{object.finish_date}}</h6>
            <!-- <a href="{{ object.discourse_url }}" target="_blank"><button type="button" class="btn btn-primary btn-md btn-block mt-4 rounded-0 disclosure font-weight-light">Talk on Discourse</button></a> -->
            <a href="{{ object.discourse_url }}" target="_blank"><button type="button" class="btn btn-block btn-md btn-lg">Talk on Discourse</button></a>
          </div>
        </div>
        <div class="col-sm-12 col-md-9">
          <div class="p-2">
            <h5 class="heading pl-3">About {{object.username}}</h5>
            <p class="pl-3 description py-1">{{object.introduction}}</p>
          </div>
          <div class="p-2">
            <h5 class="heading pl-3">Projects</h5>
            <p class="pl-3 description py-1">{{object.work_done}}</p>
          </div>
          <div class="p-2">
            <h5 class="heading pl-3">Favorite Experience</h5>
            <p class="pl-3 description py-1">{{object.fav_experience}}</p>
          </div>
        </div>
      </div>
  </body>
{% endblock content %}

{% block press_section %}
{% endblock press_section %}

<footer>
{% block footer %}
  {{ block.super }}
{% endblock footer %}
</footer>